# Generated by Django 5.2.4 on 2025-07-11 02:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCHRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BCH Rate',
                'verbose_name_plural': 'BCH Rates',
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoreOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('score', models.CharField(max_length=20)),
                ('bch_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('bet_count', models.IntegerField(default=0)),
                ('last_monitored_tx_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='api.match')),
            ],
            options={
                'unique_together': {('match', 'score')},
            },
        ),
        migrations.CreateModel(
            name='RealBetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=64, unique=True)),
                ('bch_address', models.CharField(max_length=50)),
                ('amount_satoshi', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.scoreoutcome')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='winning_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='api.scoreoutcome'),
        ),
    ]
