# Generated by Django 5.2.4 on 2025-07-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
