# Generated by Django 5.2.3 on 2025-07-08 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoreOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('score', models.CharField(max_length=20)),
                ('bch_address', models.CharField(blank=True, max_length=255, null=True)),
                ('bet_count', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='api.match')),
            ],
            options={
                'unique_together': {('match', 'score')},
            },
        ),
    ]
