from django.urls import path, include # Ensure 'include' is imported
from rest_framework.routers import DefaultRouter
# Import all necessary ViewSets from your api.views
from api.views import MatchViewSet, ScoreOutcomeViewSet, BCHRateViewSet, RealBetTransactionViewSet, SimulatePredictionView

# Create a router instance
router = DefaultRouter()

# Register your ViewSets with the router.
# The router will automatically generate URL patterns for CRUD operations.
router.register(r'matches', MatchViewSet)
router.register(r'outcomes', ScoreOutcomeViewSet)
# For BCHRateViewSet, basename is required because it's ReadOnlyModelViewSet
# and doesn't have a direct queryset to infer a name from.
router.register(r'bch-rate', BCHRateViewSet, basename='bch-rate')
router.register(r'transactions', RealBetTransactionViewSet, basename='transactions')

# Define urlpatterns for your API.
# The router.urls will handle /api/matches/, /api/outcomes/, /api/bch-rate/, etc.
urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)), # This makes the router URLs accessible directly under /api/
    
    # Define the custom URL for simulate-prediction, as it's a custom action on a ViewSet
    # .as_view({'post': 'simulate_prediction'}) maps POST requests to the simulate_prediction method
    path('simulate-prediction/', SimulatePredictionView.as_view({'post': 'simulate_prediction'}), name='simulate-prediction'),
]